Algoritmo "algoritmo10"

Var

   dividendo, divisor, quociente, resto : inteiro

Inicio

   escreva("Digite o dividendo: ")
   leia(dividendo)

   escreva("Digite o divisor: ")
   leia(divisor)

   quociente <- dividendo div divisor
   resto <- dividendo mod divisor

   escreval("Dividendo: ", dividendo)
   escreval("Divisor: ", divisor)
   escreval("Quociente: ", quociente)
   escreval("Resto: ", resto)
Fimalgoritmo
